const SET_INSPECTION_DATE = 'SET_INSPECTION_DATE';
const ECP_EXPIRY_DATE = 'ECP_EXPIRY_DATE';
const ECIR_EXPIRY_DATE = 'ECIR_EXPIRY_DATE';
const GAS_SAFETY_METER_DATE = 'GAS_SAFETY_METER_DATE';
const IS_ELECTRY_METER = 'IS_ELECTRY_METER';
const ELECTRICY_METER_READING = 'ELECTRICY_METER_READING';
const IS_GAS_METER = 'IS_GAS_METER';
const GAS_METER_READING = '';
const WATER_METER = 'WATER_METER';
const SMOKE_ALARAM = 'SMOKE_ALARAM';
const CO_ALARAM = 'CO_ALARAM';
const HEATING_SYSTEM = 'HEATING_SYSTEM';
const FINAL_REMAKRS = 'FINAL_REMAKRS';
const INSPECTOR_SIGNATURE = 'INSPECTOR_SIGNATURE';
const TENANT_SIGNATURE = 'TENANT_SIGNATURE';
export {
  SET_INSPECTION_DATE,
  ECP_EXPIRY_DATE,
  ECIR_EXPIRY_DATE,
  GAS_SAFETY_METER_DATE,
  IS_GAS_METER,
  IS_ELECTRY_METER,
  ELECTRICY_METER_READING,
  GAS_METER_READING,
  WATER_METER,
  SMOKE_ALARAM,
  CO_ALARAM,
  HEATING_SYSTEM,
  FINAL_REMAKRS,
  TENANT_SIGNATURE,
  INSPECTOR_SIGNATURE,
};
